# Generated by Django 3.0.7 on 2020-06-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_peroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('tz', models.CharField(max_length=30)),
                ('activity_peroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activity_peroid')),
            ],
        ),
    ]
